# Generated by Django 4.2.1 on 2023-05-31 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_imageurl_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
    ]
