# Generated by Django 4.2.1 on 2023-05-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_images_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
