# Generated by Django 4.2.1 on 2023-05-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
