# Generated by Django 4.2.1 on 2023-06-01 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_full_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_first_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_phone_number', models.CharField(max_length=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
            options={
                'verbose_name': 'информация о заказе',
                'verbose_name_plural': 'информация о заказах',
            },
        ),
    ]
