# Generated by Django 4.2.1 on 2023-06-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='delivery_method',
            field=models.CharField(choices=[('самовывоз', 'самовывоз'), ('доставка курьером', 'доставка курьером'), ('транспортной компанией', 'транспортной компанией')], default='самовывоз', max_length=255),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='recipient_address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
    ]
