# Generated by Django 4.2.1 on 2023-06-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_orderinfo_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=12, default=None, max_digits=20),
        ),
    ]
