# Generated by Django 4.2.1 on 2023-06-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_used_bonuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='discount',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
