# Generated by Django 4.2.1 on 2023-06-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_orderinfo_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True),
        ),
    ]
