version: '3.7'
services:
  web:
    build:
      dockerfile: Dockerfile.prod
    command: gunicorn sadtech.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000:8000
    env_file:
      - sadtech/.env.prod
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - sadtech/.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: